# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9ad727b4fd5cbd37f6d9b251de18b6a3bc0961a0c2951d55b46fb30e20761d0e40ab6cc8c81ff939ce2d7a3c4b675b19c78e6256ad1b3bce318435c4b3bdbbe

test:
  secret_key_base: 0994dc3da883abc656173553f1f3bad944d7ebb2eac09ee15e3aaad012c39c8366ec871c5f322c59c938afb033028a33f528de5ffbe976859d86ff804047bcc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
